FROM python:3.14.6-alpine3.24

WORKDIR /

COPY requirements.txt /

RUN pip install --no-cache-dir -r requirements.txt
RUN apk add --no-cache build-base linux-headers

COPY app.py /
COPY core/ /core/
COPY templates/ /templates/

ENV redis_host=redis
EXPOSE 8000
CMD ["python3", "-m", "gunicorn", "-w", "8", "-b", "0.0.0.0:8000", "--worker-class", "gevent", "app:app"]